### ISSUE TITLE
Upgrade to the new compiler 0.11

### ISSUE THREAD

**Issue by klangner** [jacereda/purescript-statistics#1]
Hi,

Do you have plans to upgrade this library to the new compiler?

**Comment by klangner** [comment]
BTW.

I would be interesed in porting Haskell statistics library to the PureScript. Do you think this library can be used for this or better start new one?

https://hackage.haskell.org/package/statistics

**Comment by jacereda** [comment]
Hi,

I've updated it and tagged as 0.1.0. 

As for the haskell port, that package plays in another league, I don't think my current code could be of any use for that task.
