### ISSUE TITLE
Upgrade to latest purescript libraries, compiler, spago

### ISSUE THREAD

**Issue by tfc** [jacereda/purescript-statistics#2]
Hi,

I just forked this repository to be able to use it in a project of mine: https://github.com/tfc/purescript-statistics

I am also interested to get it upstream into the package registry so that the package can simply be used using spago.
What's the best way in your opinion? I would open a pull request so we can get all the changes in your original repo and upstream afterwards. When we do that, i am not sure what to do with the bower files as I started using purescript when spago was already seemingly the standard.

**Comment by jacereda** [comment]
I can add you as a maintainer if you're OK with that. I'm away from PS these days and I'm a bit disconnected, but if spago is the way to go now just get rid of the bower stuff.

**Comment by tfc** [comment]
Yes, please.

**Comment by jacereda** [comment]
Done.
